### PR TITLE
add er-aml criterion tests

### PR DESCRIPTION
**Pull request by GeremiaPompei**

### CODE REVIEW

**Review by AndreaCossu — CHANGES_REQUESTED** [review]
Hi @GeremiaPompei , thanks for the contribution! Can you please add SingleHeadReducedResNet18 to the __all__ at the bottom of the file?

**Comment by GeremiaPompei** [comment]
Hi @AndreaCossu, I moved the model in another file and renamed it in FEResNet18. I thought that could be a good idea to keep it independent. Tell me if is better or not that in case I will modify it.

**Comment by GeremiaPompei** [comment]
@AndreaCossu  Sorry I messed up with PR, I should have closed the other. For ER-AML I need ResNet18 with a way to access to the feature extractor of the model. What do you think about it? Also for me is useless to write repeated code of resnet18 in another file only for this little update

**Comment by AndreaCossu** [comment]
I agree, I would keep only one file. Adding the feature extraction method in your class like you did in this PR looks fine to me. If you just add the class to the __all__ list I think we can merge this.

**Comment by GeremiaPompei** [comment]
@AndreaCossu  Ok I should have done with the last commit

**Comment by AndreaCossu** [comment]
In `models/reduced_resnet18.py` I am still seeing only the multi-headed class in the `__all__` list.

**Comment by GeremiaPompei** [comment]
@AndreaCossu  I messed up with my local branches, now it should be fixed

**Comment by AndreaCossu** [comment]
Great thanks!

**Review by AndreaCossu — APPROVED** [review]

**Comment by AndreaCossu** [comment]
@GeremiaPompei I just noticed that the replay memory is quite large in the arguments of the experiments. Is this required to obtain the original performance? I believe the original paper uses much less memory.

**Comment by GeremiaPompei** [comment]
@AndreaCossu in the original paper is used all the memory to sample positive and negative examples for ER_AML strategy. In the code of the original paper the memory is handled in a different way. The code is available in the following link https://github.com/pclucas14/AML. I have already talked about this with @AntonioCarta and @AlbinSou in the PR on avalanche repo. I decided to solve this problem using a dataloader for each class in the memory that sample a each time a number of examples that are equal to the minibatch training size. If this is not a good solution we can talk about this in a call.

**Pull request merged**
