### PR TITLE
Added er mir test

### PR DESCRIPTION
**Pull request by AlbinSou**
I added the files to reproduce ER-MIR results. It looks like it corresponds to the one from the paper (Split Cifar10 and Split MNIST). 
However, there are a few caveats that I will list below and maybe we can look to fix:
- The learning rate at which I get results similar to the paper for Split-Cifar10 is 0.05, but they use 0.1 in the paper.
- Even though the final accuracy for Split-Cifar10 is similar to the one of the paper, the progression is strange, I would expect something like that (average accuracy after each task): 0.8, 0.7, 0.6, 0.5, 0.47, but I get something like this:  0.8, 0.45, 0.46, 0.45, 0.47. I don't know why it behaves like that. This might be worth investigating. Maybe it's due to the fact that I am not using incremental classifier because in the current avalanche version it is not compatible with online scenario.
- I added a permuted mnist experiment, however for some reason I don't know, it hangs on the first training batch. Maybe after reviewing the code someone has an idea of why this is hanging like this.
-  I also added a function to experiments.utils, to reduce the size of the mnist datasets as done in the paper. Let me know if you want me to put this somewhere else.

### CODE REVIEW

**Comment by AntonioCarta** [comment]
@AndreaCossu what do you think?

- having slightly different hyperparameters is ok. Just remember to add a docstring/comment to the experiments where you reference the paper and describe the differences.
- Regarding permuted MNIST, we recently investigated a huge slowdown due to transformations, Andrea will push the fix soon.

**Comment by AndreaCossu** [comment]
Thanks @AlbinSou !
1. It's not a problem if learning rate is different. We ended up using different hyper-parameters even for other strategies.
2. Thanks for pointing this out, I'll open an issue highlighting the problem once I merge this PR.
3. Permuted MNIST should be fixed now in the main branch of avalanche. Can you please try again and let me know if the problem persists?
4. The utils module is fine for now.

**Comment by AlbinSou** [comment]
> Thanks @AlbinSou !
> 
> 1. It's not a problem if learning rate is different. We ended up using different hyper-parameters even for other strategies.
> 2. Thanks for pointing this out, I'll open an issue highlighting the problem once I merge this PR.
> 3. Permuted MNIST should be fixed now in the main branch of avalanche. Can you please try again and let me know if the problem persists?
> 4. The utils module is fine for now.

So, I tried again to run the test with permuted mnist but I still get the slow-down. Actually it's not even a slow down, I just can't get past the first iteration. I will investigate that on my side.

However, I wanted to point out smt as I am not sure if it's a bug or not. I had put in the train_transform and eval_transform fields of the split and permuted mnist test only the ToTensor() transform because I don't think the authors use any transforms in the paper. If was working fine with the Split Mnist example but now with the new version it is not working anymore. When I remove the transformations it works fine.

I get the following error when iterating on the normal dataloader (not the one I use for replay): 

TypeError: pic should be PIL Image or ndarray, got class torch.Tensor

Is it a known bug? In any case it might be worth investigating.

**Comment by AlbinSou** [comment]
> > I fixed it locally by not creating the replay loader unless the dataset is bigger than the batch size. (mir.py:127 should be if len(buffer) > self.batch_size_mem:, instead of 0) , how should I update it in the avalanche repo, doing another pull request for the fix ?
> 
> yes, please submit a PR.
> 
> > I wanted to point out something else as I am not sure if it's a bug or not. I had put in the train_transform and eval_transform fields of the split and permuted mnist test only the ToTensor() transform because I don't think the authors use any transforms in the paper. If was working fine with the Split Mnist example but now with the new version it is not working anymore. When I remove the transformations it works fine.
> 
> We recently changed permuted MNIST to use tensors instead of images (preprocessing was a major source of slowdown). If you already had custom transform from an earlier avalanche version it's normal that you needed to change them.
> 
> > I get the following error when iterating on the normal dataloader (not the one I use for replay):
> > TypeError: pic should be PIL Image or ndarray, got class torch.Tensor
> 
> Again, looks related to the change we did to Permuted MNIST transforms. You call `ToTensor` on an input which is already a tensor.

Ok I will change the code by putting transforms to None and this should be it. Sorry for the issue I had not seen this answer.

**Comment by AndreaCossu** [comment]
Thanks @AlbinSou , if you can pull from the master and confirm that everything looks good on your side I can merge this.

**Comment by AndreaCossu** [comment]
Did you sync with the master in your latest commit? Let me know when I can merge it 😄

**Comment by AlbinSou** [comment]
> Did you sync with the master in your latest commit? Let me know when I can merge it smile

Hello @AndreaCossu. Yes I did this I believe. Let me know if you see any problem but I think they are no conflicts anymore.

**Review by AndreaCossu — APPROVED** [review]

**Pull request merged**
